# Generated by Django 5.2.9 on 2025-12-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0003_alter_laundryorder_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
