# Generated by Django 5.2.9 on 2025-12-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0004_alter_customer_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingtype',
            name='urgent_price',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Price for urgent delivery', max_digits=10),
            preserve_default=False,
        ),
    ]
