# Generated by Django 5.2.9 on 2025-12-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0005_clothingtype_urgent_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryorder',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='laundryorder',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='laundryorder',
            name='urgent_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
