# Generated by Django 5.2.9 on 2025-12-28 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0006_laundryorder_subtotal_laundryorder_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laundryorder',
            name='total',
        ),
        migrations.RemoveField(
            model_name='laundryorder',
            name='total_amount',
        ),
    ]
