# Generated by Django 5.2.9 on 2025-12-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0007_remove_laundryorder_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='rewashing',
            field=models.BooleanField(default=False, help_text='If checked, item is free (rewash)'),
        ),
    ]
