# Generated by Django 5.2.9 on 2025-12-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0008_orderitem_rewashing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundryorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('washing', 'Washing'), ('ironing', 'Ironing'), ('ready', 'Ready'), ('collected', 'Collected'), ('not_collected', 'Not Collected')], default='pending', max_length=20),
        ),
    ]
