# Generated by Django 5.2.9 on 2025-12-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0009_alter_laundryorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='customer',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
