# Generated by Django 5.2.9 on 2025-12-31 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0010_customer_alternate_phone_customer_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundryorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='laundry.customer'),
        ),
    ]
